[Variables]

Color=255,255,255,255
Font=Google Sans
Wind=3.6
//If using Imperial or m/s change this value to 1
WindUnit=km/h
//If using Imperial change to mph; If using m/s change to m/s
units=M
//Options M (metric), I (imperial), S (scientific)
//Converts from m/s to specified units
//1 m/s = 3.6 km/h
//1 m/s = 2.23694 mph
lon=LON
lat=LAT
city=CITY
postal=POSTAL
city_id=CITY_ID
//Change above values to the ones for your location. Only 1 of lat&lon/city/postal/city_id needs to be filled out
api=API_KEY