[Variables]

Color=255,255,255,255
ColorBlack=0,0,0,255
Font=Google Sans
WindUnit=km/h
//If using Imperial change to mph; If using m/s change to m/s
units=auto
//Options:
//auto: automatically select units based on geographic location
//ca: same as si, except that windSpeed and windGust are in kilometers per hour
//uk2: same as si, except that nearestStormDistance and visibility are in miles, and windSpeed and windGust in miles per hour
//us: Imperial units (the default)
//si: SI units

lon=LON
lat=LAT
api=API_KEY
lang=en