blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/cloneofghosts/Google-Weather-Card/discussions
    about: Please ask and answer questions here.
