name: Enhancement
description: Suggest an enhancement to an existing weather card.
labels: ["enhancement", "Needs Review"]
projects: ["cloneofghosts/1"]
body:

  - type: textarea
    id: describe-enhancement
    attributes:
      label: Describe Enhacement
      description: Describe your enhancement here.
    validations:
      required: true

  - type: dropdown
    id: weather-provider
    attributes:
      label: Weather Provider
      options: 
        - WeatherBit
        - OpenWeatherMap
        - Met Office
        - Tomorrow.io
        - Here
        - Visual Crossing
        - WeatherAPI.com
        - PirateWeather
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Achknowledgements
      options:
        - label: I have updated the weather card to the latest version.
          required: true
        - label: I have searched the repository for a similar issue.
          required: true
        - label: I have written a descriptive title.
          required: true
