name: New Source
description: Suggest a new weather source to use in a weather card.
labels: ["enhancement", "New Source" , "Needs Review]
body:

  - type: input
    id: documentation-url
    attributes:
      label: Weather Source Documentation
      description: Link to the publicly available documentation URL
      placeholder: |
        Example: "https://xxx.xxx"
    validations:
      required: true
      
  - type: textarea
    id: source-details
    attributes:
      label: Weather Source Details
      description: Details on what the weather source offers.
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Achknowledgements
      options:
        - label: The weather source has a free tier available and is not just a free trial for a paid API.
          required: true
        - label: The weather source has a current and daily forecast available.
          required: true
        - label: I have searched the repository for a similar issue.
          required: true
        - label: I have included the name of the weather source in the issue title.
          required: true