[Variables]

Color=255,255,255,255
ColorBlack=0,0,0,255
Font=Google Sans
Wind=3.6
//If using Imperial or m/s change this value to 1
WindUnit=km/h
//If using Imperial change to mph; If using m/s change to m/s
units=metric
//Options:
//metric and imperial

lon=LON
lat=LAT
api=API
lang=en
Language=English
CurrentRate=3600
// Update time in seconds
// 30 minutes is 1800
// 1 hour is 3600
ForecastRate=10800
// Update time in seconds
// 30 minutes is 1800
// 1 hour is 3600