[Variables]

Color=255,255,255,255
ColorBlack=0,0,0,255
Font=Google Sans
Wind=3.6
//If using Imperial or m/s change this value to 1
WindUnit=km/h
//If using Imperial change to mph; If using m/s change to m/s
units=si
//Options:
//metric and imperial

RateCurrent=1800 //every 30 minutes
RateForecast=10800 //every 3 hours
// Update time in seconds
// 30 minutes is 1800
// 1 hour is 3600

lon=LON
lat=LAT
api=API
Language=English